import { INFT } from "./interfaces/INFT.ts";

export const NFTS: INFT[] = [
  {
    id: 1,
    photo: "X",
    title: "title",
    author: "Ishak",
    type: "type",
    priceType: "priceType",
    price: 100,
  },
  {
    id: 2,
    photo: "X",
    title: "The Holy Grail",
    author: "Pixart Motion",
    type: "cat",
    priceType: "Fixed",
    price: 0.001,
  },
  {
    id: 3,
    photo: "X",
    title: "The Holy Grail",
    author: "Pixart Motion",
    type: "cat",
    priceType: "Fixed",
    price: 0.001,
  },
  {
    id: 4,
    photo: "X",
    title: "The Holy Grail",
    author: "Pixart Motion",
    type: "cat",
    priceType: "Fixed",
    price: 0.001,
  },
  {
    id: 5,
    photo: "X",
    title: "The Holy Grail",
    author: "Pixart Motion",
    type: "cat",
    priceType: "Fixed",
    price: 0.001,
  },
  {
    id: 6,
    photo: "X",
    title: "The Holy Grail",
    author: "Pixart Motion",
    type: "cat",
    priceType: "Fixed",
    price: 0.001,
  },
  {
    id: 7,
    photo: "X",
    title: "The Holy Grail",
    author: "Pixart Motion",
    type: "cat",
    priceType: "Fixed",
    price: 0.001,
  },
  {
    id: 8,
    photo: "X",
    title: "8",
    author: "Pixart Motion",
    type: "cat",
    priceType: "Fixed",
    price: 0.001,
  },
  // {
  //   id: 9,
  //   photo: "X",
  //   title: "9",
  //   author: "Pixart Motion",
  //   type: "cat",
  //   priceType: "Fixed",
  //   price: 0.001,
  // },
  // {
  //   id: 10,
  //   photo: "X",
  //   title: "10",
  //   author: "Pixart Motion",
  //   type: "cat",
  //   priceType: "Fixed",
  //   price: 0.001,
  // },
];
